# train
train:
    init: false
    train_file:
        user: ../data/user.dat
        item: ../data/item.dat
        sample: ../data/sample.dat
    seq_len: 50
    negsample: 10
    batch_size: 1024
    epochs: 10

#
feat:
    feat_file: ../models/feature_label.pkl
    emb_dim: 8
model:
    embedding_dim: 32
    weights_save: ../models/dssm_weights.h5
    item_emb: ../models/item.emb
    user_emb: ../models/user.emb

